[build-system]
requires = ["setuptools", "nimporter==2.0.0"]
build-backend = "setuptools.build_meta"

[project]
name = "save-monger"
version = "0.4.0"
dependencies = ['pydantic']
requires-python = ">= 3.10"

[tool.setuptools]
packages = ["save_monger"]